spring:
  application:
    name: jpademo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Bo2006$han08*
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true